[[https://gitter.im/WillianPaiva/dominion_datamining?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge][https://badges.gitter.im/WillianPaiva/dominion_datamining.svg]] [[https://travis-ci.org/WillianPaiva/dominion_datamining][https://travis-ci.org/WillianPaiva/dominion_datamining.svg?branch=master]] [[https://trello.com/b/mU21Z9aA][https://github.com/WillianPaiva/dominion_datamining/blob/master/icons/trello.png?raw=true = 10x10]] [[https://github.com/syl20bnr/spacemacs][file:https://cdn.rawgit.com/syl20bnr/spacemacs/442d025779da2f62fc86c2082703697714db6514/assets/spacemacs-badge.svg]]



* Dominion Data mining

** dependencies
  - mongodb
  - java 1.7
  - maven
  - tar
*** mongoDB
to rum the parser a running instance of *mongod* on port 27020 is required.
in case of using a system wide installation just make sure the *mongod* process is running on port 27020


** running the parser
*before running the parser you need to place all the tar.bz2 files on the folder sampleLogs*

if a system wide instance of *mongod* is being used just run the *execute* on the root folder of the repository.

if no instance of *mongod* run the *startMongo* on the root folder of the repository which will create create a local installation of mongoDB
inside the repository directory and execute the *mongod* on the good parameters.
then run the *execute* on the root folder of the repository.
Or just use the *allInOne* executable which will take care of *mongo* and run the program.


** the Database
after the parser is finished the database can be found inside the folder *mongoData*
