from bson.objectid import ObjectId
import datetime

dummy = {'log': [{'playersMove': [{'plays': [{'type': 'plays',
                                              'following': [],
                                              'cards': {'copper': 3}},
                                             {'type': 'buys',
                                              'following': [],
                                              'cards': {'fishingvillage': 1}},
                                             {'type': 'draws',
                                              'following': [],
                                              'cards': {'copper': 4,
                                                        'estate': 1}}],
                                   'name': 'kloijh'},
                                  {'plays': [{'type': 'draws',
                                              'following': [],
                                              'cards': {'copper': 5}}],
                                   'name': 'Anuski'}],
                  'turn': 1},
                 {'playersMove': [{'plays': [{'type': 'plays',
                                              'following': [],
                                              'cards': {'copper': 4}},
                                             {'type': 'buys',
                                              'following': [],
                                              'cards': {'spicemerchant': 1}},
                                             {'type': 'draws',
                                              'following': [],
                                              'cards': {'fishingvillage': 1,
                                                        'copper': 3,
                                                        'estate': 1}}],
                                   'name': 'kloijh'},
                                  {'plays': [{'type': 'plays',
                                              'following': [],
                                              'cards': {'copper': 5}},
                                             {'type': 'buys',
                                              'following': [],
                                              'cards': {'tradingpost': 1}},
                                             {'type': 'draws',
                                              'following': [],
                                              'cards': {'copper': 3,
                                                        'estate': 1,
                                                        'tradingpost': 1}}],
                                   'name': 'Anuski'}],
                  'turn': 2},
                 {'playersMove': [{'plays': [{'type': 'plays',
                                              'following': [],
                                              'cards': {'fishingvillage': 1}},
                                             {'type': 'plays',
                                              'following': [],
                                              'cards': {'copper': 3}},
                                             {'type': 'buys',
                                              'following': [],
                                              'cards': {'silver': 1}},
                                             {'type': 'draws',
                                              'following': [],
                                              'cards': {'spicemerchant': 1,
                                                        'copper': 3,
                                                        'estate': 1}}],
                                   'name': 'kloijh'},
                                  {'plays': [{'type': 'plays',
                                              'following': [{'type': 'trash',
                                                             'following': [],
                                                             'cards': {'copper': 1,
                                                                       'estate': 1}},
                                                            {'type': 'gains',
                                                             'following': [],
                                                             'cards': {'silver': 1}}],
                                              'cards': {'tradingpost': 1}},
                                             {'type': 'plays',
                                              'following': [],
                                              'cards': {'copper': 2,
                                                        'silver': 1}},
                                             {'type': 'buys',
                                              'following': [],
                                              'cards': {'fishingvillage': 1}},
                                             {'type': 'draws',
                                              'following': [],
                                              'cards': {'copper': 3,
                                                        'estate': 2}}],
                                   'name': 'Anuski'}],
                  'turn': 3},
{'playersMove': [{'plays': [{'type': 'plays',
                             'following': [{'type': 'trash',
                                            'following': [],
                                            'cards': {'copper': 1}}],
                             'cards': {'spicemerchant': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'copper': 3}},
                            {'type': 'buys',
                             'following': [],
                             'cards': {'silver': 1}},
                            {'type': 'draws',
                             'following': [],
                             'cards': {'spicemerchant': 1,
                                       'fishingvillage': 1,
                                       'copper': 2,
                                       'estate': 1}}],
                  'name': 'kloijh'},
                 {'plays': [{'type': 'plays',
                             'following': [],
                             'cards': {'copper': 3}},
                            {'type': 'buys',
                             'following': [],
                             'cards': {'workshop': 1}},
                            {'type': 'draws',
                             'following': [],
                             'cards': {'fishingvillage': 1,
                                       'copper': 2,
                                       'estate': 2}}],
                  'name': 'Anuski'}],
 'turn': 4},
{'playersMove': [{'plays': [{'type': 'plays',
                             'following': [],
                             'cards': {'fishingvillage': 1}},
                            {'type': 'plays',
                             'following': [{'type': 'trash',
                                            'following': [],
                                            'cards': {'copper': 1}}],
                             'cards': {'spicemerchant': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'copper': 3}},
                            {'type': 'buys',
                             'following': [],
                             'cards': {'silver': 1}},
                            {'type': 'draws',
                             'following': [],
                             'cards': {'copper': 2,
                                       'estate': 1,
                                       'silver': 2}}],
                  'name': 'kloijh'},
                 {'plays': [{'type': 'plays',
                             'following': [],
                             'cards': {'fishingvillage': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'copper': 2}},
                            {'type': 'buys',
                             'following': [],
                             'cards': {'fishingvillage': 1}},
                            {'type': 'draws',
                             'following': [],
                             'cards': {'copper': 4,
                                       'silver': 1}}],
                  'name': 'Anuski'}],
 'turn': 5},
{'playersMove': [{'plays': [{'type': 'plays',
                             'following': [],
                             'cards': {'copper': 2,
                                       'silver': 2}},
                            {'type': 'buys',
                             'following': [{'type': 'gains',
                                            'following': [],
                                            'cards': {'tradingpost': 1}}],
                             'cards': {'bordervillage': 1}},
                            {'type': 'draws',
                             'following': [],
                             'cards': {'fishingvillage': 1,
                                       'copper': 2,
                                       'estate': 1,
                                       'tradingpost': 1}}],
                  'name': 'kloijh'},
                 {'plays': [{'type': 'plays',
                             'following': [],
                             'cards': {'copper': 4,
                                       'silver': 1}},
                            {'type': 'buys',
                             'following': [{'type': 'gains',
                                            'following': [],
                                            'cards': {'cache': 1}},
                                           {'type': 'gains',
                                            'following': [],
                                            'cards': {'copper': 2}}],
                             'cards': {'bordervillage': 1}},
                            {'type': 'draws',
                             'following': [],
                             'cards': {'silver': 1,
                                       'tradingpost': 1,
                                       'copper': 1,
                                       'cache': 1,
                                       'workshop': 1}}],
                  'name': 'Anuski'}],
 'turn': 6},
{'playersMove': [{'plays': [{'type': 'plays',
                             'following': [],
                             'cards': {'fishingvillage': 1}},
                            {'type': 'plays',
                             'following': [{'type': 'trash',
                                            'following': [],
                                            'cards': {'copper': 1,
                                                      'estate': 1}},
                                           {'type': 'gains',
                                            'following': [],
                                            'cards': {'silver': 1}}],
                             'cards': {'tradingpost': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'copper': 1,
                                       'silver': 1}},
                            {'type': 'buys',
                             'following': [],
                             'cards': {'silver': 1}},
                            {'type': 'draws',
                             'following': [],
                             'cards': {'spicemerchant': 1,
                                       'copper': 1,
                                       'estate': 1,
                                       'silver': 2}}],
                  'name': 'kloijh'},
                 {'plays': [{'type': 'plays',
                             'following': [{'type': 'gains',
                                            'following': [],
                                            'cards': {'fishingvillage': 1}}],
                             'cards': {'workshop': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'copper': 1,
                                       'cache': 1,
                                       'silver': 1}},
                            {'type': 'buys',
                             'following': [],
                             'cards': {'gold': 1}},
                            {'type': 'draws',
                             'following': [],
                             'cards': {'fishingvillage': 1,
                                       'copper': 4}}],
                  'name': 'Anuski'}],
 'turn': 7},
{'playersMove': [{'plays': [{'type': 'plays',
                             'following': [{'type': 'trash',
                                            'following': [],
                                            'cards': {'copper': 1}}],
                             'cards': {'spicemerchant': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'silver': 2}},
                            {'type': 'buys',
                             'following': [{'type': 'gains',
                                            'following': [],
                                            'cards': {'library': 1}}],
                             'cards': {'bordervillage': 1}},
                            {'type': 'draws',
                             'following': [],
                             'cards': {'bordervillage': 1,
                                       'copper': 2,
                                       'estate': 1,
                                       'silver': 1}}],
                  'name': 'kloijh'},
                 {'plays': [{'type': 'plays',
                             'following': [],
                             'cards': {'fishingvillage': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'copper': 4}},
                            {'type': 'buys',
                             'following': [],
                             'cards': {'spicemerchant': 1}},
                            {'type': 'draws',
                             'following': [],
                             'cards': {'copper': 3,
                                       'estate': 2}}],
                  'name': 'Anuski'}],
 'turn': 8},
{'playersMove': [{'plays': [{'type': 'plays',
                             'following': [],
                             'cards': {'bordervillage': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'copper': 2,
                                       'silver': 2}},
                            {'type': 'buys',
                             'following': [{'type': 'gains',
                                            'following': [],
                                            'cards': {'library': 1}}],
                             'cards': {'bordervillage': 1}},
                            {'type': 'draws',
                             'following': [],
                             'cards': {'fishingvillage': 1,
                                       'copper': 1,
                                       'library': 1,
                                       'estate': 1,
                                       'silver': 1}}],
                  'name': 'kloijh'},
                 {'plays': [{'type': 'plays',
                             'following': [],
                             'cards': {'copper': 3}},
                            {'type': 'buys',
                             'following': [],
                             'cards': {'fishingvillage': 1}},
                            {'type': 'draws',
                             'following': [],
                             'cards': {'bordervillage': 1,
                                       'fishingvillage': 2,
                                       'cache': 1,
                                       'estate': 1}}],
                  'name': 'Anuski'}],
 'turn': 9},
{'playersMove': [{'plays': [{'type': 'plays',
                             'following': [],
                             'cards': {'fishingvillage': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'library': 1}},
                            {'type': 'plays',
                             'following': [{'type': 'trash',
                                            'following': [],
                                            'cards': {'copper': 1}}],
                             'cards': {'spicemerchant': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'bordervillage': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'bordervillage': 1}},
                            {'type': 'plays',
                             'following': [{'type': 'trash',
                                            'following': [],
                                            'cards': {'estate': 2}},
                                           {'type': 'gains',
                                            'following': [],
                                            'cards': {'silver': 1}}],
                             'cards': {'tradingpost': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'library': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'copper': 1,
                                       'silver': 6}},
                            {'type': 'buys',
                             'following': [],
                             'cards': {'province': 1}},
                            {'type': 'draws',
                             'following': [],
                             'cards': {'bordervillage': 1,
                                       'copper': 2,
                                       'library': 1,
                                       'silver': 1}}],
                  'name': 'kloijh'},
                 {'plays': [{'type': 'plays',
                             'following': [],
                             'cards': {'fishingvillage': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'fishingvillage': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'bordervillage': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'cache': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'copper': 1}},
                            {'type': 'buys',
                             'following': [],
                             'cards': {'gold': 1}},
                            {'type': 'draws',
                             'following': [],
                             'cards': {'fishingvillage': 1,
                                       'copper': 3,
                                       'workshop': 1}}],
                  'name': 'Anuski'}],
'turn': 10},
{'playersMove': [{'plays': [{'type': 'plays',
                             'following': [],
                             'cards': {'bordervillage': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'bordervillage': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'library': 1}},
                            {'type': 'plays',
                             'following': [{'type': 'trash',
                                            'following': [],
                                            'cards': {'copper': 1}}],
                             'cards': {'spicemerchant': 1}},
                            {'type': 'plays',
                             'following': [{'type': 'trash',
                                            'following': [],
                                            'cards': {'copper': 1,
                                                      'silver': 1}},
                                           {'type': 'gains',
                                            'following': [],
                                            'cards': {'silver': 1}}],
                             'cards': {'tradingpost': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'library': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'bordervillage': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'silver': 6}},
                            {'type': 'buys',
                             'following': [],
                             'cards': {'province': 1}},
                            {'type': 'draws',
                             'following': [],
                             'cards': {'province': 1,
                                       'bordervillage': 2,
                                       'silver': 2}}],
                  'name': 'kloijh'},
                 {'plays': [{'type': 'plays',
                             'following': [],
                             'cards': {'fishingvillage': 1}},
                            {'type': 'plays',
                             'following': [{'type': 'gains',
                                            'following': [],
                                            'cards': {'fishingvillage': 1}}],
                             'cards': {'workshop': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'copper': 3}},
                            {'type': 'buys',
                             'following': [{'type': 'gains',
                                            'following': [],
                                            'cards': {'cache': 1}},
                                           {'type': 'gains',
                                            'following': [],
                                            'cards': {'copper': 2}}],
                             'cards': {'bordervillage': 1}},
                            {'type': 'draws',
                             'following': [],
                             'cards': {'spicemerchant': 1,
                                       'fishingvillage': 1,
                                       'copper': 2,
                                       'tradingpost': 1}}],
                  'name': 'Anuski'}],
'turn': 11},
{'playersMove': [{'plays': [{'type': 'plays',
                             'following': [],
                             'cards': {'bordervillage': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'bordervillage': 1}},
                            {'type': 'plays',
                             'following': [{'type': 'discard',
                                            'following': [],
                                            'cards': {'library': 1}}],
                             'cards': {'library': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'fishingvillage': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'bordervillage': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'silver': 4}},
                            {'type': 'buys',
                             'following': [],
                             'cards': {'province': 1}},
                            {'type': 'draws',
                             'following': [],
                             'cards': {'spicemerchant': 1,
                                       'bordervillage': 1,
                                       'silver': 2,
                                       'tradingpost': 1}}],
                  'name': 'kloijh'},
                 {'plays': [{'type': 'plays',
                             'following': [],
                             'cards': {'fishingvillage': 1}},
                            {'type': 'plays',
                             'following': [{'type': 'trash',
                                            'following': [],
                                            'cards': {'copper': 1}}],
                             'cards': {'spicemerchant': 1}},
                            {'type': 'plays',
                             'following': [{'type': 'trash',
                                            'following': [],
                                            'cards': {'copper': 2}},
                                           {'type': 'gains',
                                            'following': [],
                                            'cards': {'silver': 1}}],
                             'cards': {'tradingpost': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'silver': 2}},
                            {'type': 'buys',
                             'following': [],
                             'cards': {'gold': 1}},
                            {'type': 'draws',
                             'following': [],
                             'cards': {'gold': 1,
                                       'fishingvillage': 1,
                                       'copper': 1,
                                       'bordervillage': 1,
                                       'estate': 1}}],
                  'name': 'Anuski'}],
'turn': 12},
{'playersMove': [{'plays': [{'type': 'plays',
                             'following': [],
                             'cards': {'bordervillage': 1}},
                            {'type': 'plays',
                             'following': [{'type': 'trash',
                                            'following': [],
                                            'cards': {'silver': 1}}],
                             'cards': {'spicemerchant': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'silver': 3}},
                            {'type': 'buys',
                             'following': [],
                             'cards': {'gold': 1}},
                            {'type': 'draws',
                             'following': [],
                             'cards': {'bordervillage': 2,
                                       'silver': 1}}],
                  'name': 'kloijh'},
                 {'plays': [{'type': 'plays',
                             'following': [],
                             'cards': {'fishingvillage': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'bordervillage': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'gold': 2,
                                       'copper': 1}},
                            {'type': 'buys',
                             'following': [],
                             'cards': {'province': 1}},
                            {'type': 'draws',
                             'following': [],
                             'cards': {'gold': 1,
                                       'fishingvillage': 1,
                                       'cache': 2,
                                       'workshop': 1}}],
                  'name': 'Anuski'}],
 'turn': 13},
{'playersMove': [{'plays': [{'type': 'plays',
                             'following': [],
                             'cards': {'bordervillage': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'bordervillage': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'library': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'library': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'gold': 1,
                                       'silver': 3}},
                            {'type': 'buys',
                             'following': [],
                             'cards': {'province': 1}},
                            {'type': 'draws',
                             'following': [],
                             'cards': {'spicemerchant': 1,
                                       'silver': 2,
                                       'fishingvillage': 1,
                                       'tradingpost': 1}}],
                  'name': 'kloijh'},
                 {'plays': [{'type': 'plays',
                             'following': [],
                             'cards': {'fishingvillage': 1}},
                            {'type': 'plays',
                             'following': [{'type': 'gains',
                                            'following': [],
                                            'cards': {'fishingvillage': 1}}],
                             'cards': {'workshop': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'gold': 1,
                                       'cache': 2}},
                            {'type': 'buys',
                             'following': [],
                             'cards': {'province': 1}},
                            {'type': 'draws',
                             'following': [],
                             'cards': {'bordervillage': 1,
                                       'fishingvillage': 1,
                                       'copper': 3}}],
                  'name': 'Anuski'}],
 'turn': 14},
{'playersMove': [{'plays': [{'type': 'plays',
                             'following': [],
                             'cards': {'fishingvillage': 1}},
                            {'type': 'plays',
                             'following': [{'type': 'trash',
                                            'following': [],
                                            'cards': {'silver': 1}}],
                             'cards': {'spicemerchant': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'bordervillage': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'silver': 2}},
                            {'type': 'buys',
                             'following': [],
                             'cards': {'duchy': 1}},
                            {'type': 'draws',
                             'following': [],
                             'cards': {'province': 2,
                                       'gold': 1,
                                       'library': 1,
                                       'bordervillage': 1}}],
                  'name': 'kloijh'},
                 {'plays': [{'type': 'plays',
                             'following': [],
                             'cards': {'bordervillage': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'fishingvillage': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'copper': 4}},
                            {'type': 'buys',
                             'following': [],
                             'cards': {'duchy': 1}},
                            {'type': 'draws',
                             'following': [],
                             'cards': {'spicemerchant': 1,
                                       'silver': 1,
                                       'copper': 1,
                                       'estate': 1,
                                       'tradingpost': 1}}],
                  'name': 'Anuski'}],
 'turn': 15},
{'playersMove': [{'plays': [{'type': 'plays',
                             'following': [],
                             'cards': {'bordervillage': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'bordervillage': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'library': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'library': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'gold': 1,
                                       'silver': 2}},
                            {'type': 'buys',
                             'following': [],
                             'cards': {'province': 1}},
                            {'type': 'draws',
                             'following': [],
                             'cards': {'province': 1,
                                       'spicemerchant': 1,
                                       'bordervillage': 1,
                                       'silver': 1,
                                       'tradingpost': 1}}],
                  'name': 'kloijh'},
                 {'plays': [{'type': 'plays',
                             'following': [{'type': 'trash',
                                            'following': [],
                                            'cards': {'copper': 1}}],
                             'cards': {'spicemerchant': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'fishingvillage': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'silver': 2}},
                            {'type': 'buys',
                             'following': [],
                             'cards': {'duchy': 1}},
                            {'type': 'draws',
                             'following': [],
                             'cards': {'province': 1,
                                       'fishingvillage': 1,
                                       'copper': 1,
                                       'estate': 1,
                                       'workshop': 1}}],
                  'name': 'Anuski'}],
 'turn': 16},
{'playersMove': [{'plays': [{'type': 'plays',
                             'following': [],
                             'cards': {'bordervillage': 1}},
                            {'type': 'plays',
                             'following': [{'type': 'trash',
                                            'following': [],
                                            'cards': {'silver': 1}}],
                             'cards': {'spicemerchant': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'fishingvillage': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'silver': 1}},
                            {'type': 'buys',
                             'following': [],
                             'cards': {'fishingvillage': 1}},
                            {'type': 'draws',
                             'following': [],
                             'cards': {'province': 2,
                                       'bordervillage': 1,
                                       'duchy': 1,
                                       'silver': 1}}],
                  'name': 'kloijh'},
                 {'plays': [{'type': 'plays',
                             'following': [],
                             'cards': {'fishingvillage': 1}},
                            {'type': 'plays',
                             'following': [{'type': 'gains',
                                            'following': [],
                                            'cards': {'fishingvillage': 1}}],
                             'cards': {'workshop': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'copper': 1}},
                            {'type': 'buys',
                             'following': [],
                             'cards': {'silver': 1}},
                            {'type': 'draws',
                             'following': [],
                             'cards': {'spicemerchant': 1,
                                       'bordervillage': 1,
                                       'fishingvillage': 1,
                                       'copper': 1,
                                       'cache': 1}}],
                  'name': 'Anuski'}],
 'turn': 17},
{'playersMove': [{'plays': [{'type': 'plays',
                             'following': [],
                             'cards': {'bordervillage': 1}},
                            {'type': 'plays',
                             'following': [{'type': 'discard',
                                            'following': [],
                                            'cards': {'library': 1}}],
                             'cards': {'library': 1}},
                            {'type': 'plays',
                             'following': [],
                             'cards': {'gold': 1,
                                       'silver': 2}},
                            {'type': 'buys',
                             'following': [],
                             'cards': {'province': 1}},
                            {'type': 'draws',
                             'following': [],
                             'cards': {'bordervillage': 2,
                                       'fishingvillage': 2,
                                       'silver': 1}}],
                  'name': 'kloijh'}],
 'turn': 18}],
'market': ['adventurer',
           'bordervillage',
           'cache',
           'contraband',
           'fishingvillage',
           'library',
           'spicemerchant',
           'tradingpost',
           'village',
           'workshop'],
'cardsgonne': ['province'],
'eloGap': 0,
'_id': ObjectId('56f919facff6ad4fc4c4e15f'),
'trash': {'copper': 12,
          'estate': 4,
          'silver': 4},
'players': [{'deck': {},
             'points': 39,
             'victorycards': {},
             'turns': 18,
             'strategy': 'bigmoney',
             'name': 'kloijh',
             'opening': ['fishingvillage',
                         'spicemerchant'],
             'elo': 1000,
             'firsthand': {'copper': 3,
                           'estate': 2}},
            {'deck': {'gold': 3,
                      'fishingvillage': 7,
                      'estate': 2,
                      'workshop': 1,
                      'province': 2,
                      'spicemerchant': 1,
                      'silver': 3,
                      'copper': 6,
                      'bordervillage': 2,
                      'cache': 2,
                      'tradingpost': 1},
             'points': 20,
             'victorycards': {'province': 2,
                              'estate': 2},
             'turns': 17,
             'strategy': None,
             'name': 'Anuski',
             'opening': ['tradingpost'],
             'elo': 1000,
             'firsthand': {'copper': 2,
                           'estate': 3}}],
'filename': 'game-20120510-035607-aebf280b.html',
'version': 1,
'date': datetime.datetime(2012,
                          5,
                          10,
                          1,
                          56,
                          7),
'winners': ['kloijh']}
